# Generated by Django 4.1 on 2022-11-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phnNo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
