# Generated by Django 4.1 on 2022-11-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passApp', '0002_remove_customer_id_alter_customer_phnno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phnNo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
